test:

	NODE_PATH=./lib/ jasmine-node --verbose spec/
	NODE_PATH=./lib/ node spec/test.vows.js
	NODE_PATH=./lib/ node spec/express.vows.js

express_test:
	# --use_strict
	NODE_PATH=./lib/ node spec/express.js
